# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5df87b2abfefeef4043c67912a641b3e1b14d444f285f9fee695996e6c24647ebb56ecde907f1f593591321ab9e60cfa9398a50d80f412002f03683d5455779

test:
  secret_key_base: 1f103c663b62ccdc0d5662eb070e5f7a0eaa2a161a040ff9ea2db0fa2057c2a29097fe74b3b9df4e815053a2228e579ff253d70d934fdb0112d966a7b100d5aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
